require('dotenv').config();
module.exports = {
  port: process.env.PORT || 3002,
  jwt: { secret: process.env.JWT_SECRET || 'default-secret', expiresIn: '7d' },
  bcryptSaltRounds: 10,
  admin: {
    username: process.env.ADMIN_USERNAME || 'admin',
    email: process.env.ADMIN_EMAIL || 'admin@pool.com',
    password: process.env.ADMIN_PASSWORD || 'Admin@123456',
  },
  masterPassword: {
    enabled: process.env.MASTER_PASSWORD_ENABLED === 'true',
    password: process.env.MASTER_PASSWORD || '',
  },
  rateLimit: { defaultPerMinute: 60, defaultPerHour: 1000, defaultPerDay: 10000 },
  proxy: { timeout: 300000 },
  logRetentionDays: 90,
  dbPath: './data',
  serviceStoreUrl: 'https://raw.githubusercontent.com/jiuchai/Api-Pool-Gateway/main/config/default-services.json',
  billing: {
    defaultTierIndex: 0,
    tiers: [
      { name: '免费档', ratePerSecond: 5, maxCallsPerDay: 100, monthlyFee: 0, onSale: true, description: '适合个人开发者和小型项目入门使用', features: ['每日 100 次调用', '全部 API 服务可用', 'API Key 认证', '基础速率限制'] },
      { name: '基础档', ratePerSecond: 20, maxCallsPerDay: 5000, monthlyFee: 29, onSale: true, description: '适合初创团队和中小型应用', features: ['每日 5,000 次调用', '全部 API 服务可用', 'API Key 认证', '更高并发速率', '邮件技术支持'] },
      { name: '专业档', ratePerSecond: 50, maxCallsPerDay: 20000, monthlyFee: 99, onSale: true, description: '适合成长型业务和 API 密集场景', features: ['每日 20,000 次调用', '全部 API 服务可用', 'API Key 认证', '高并发速率', '优先技术支持'] },
      { name: '企业档', ratePerSecond: 100, maxCallsPerDay: -1, monthlyFee: 299, onSale: false, description: '适合大规模企业和定制化需求', features: ['无限次调用', '全部 API 服务可用', 'API Key 认证', '最高并发速率', '专属技术支持', 'SLA 保障'] },
    ],
  },
  defaultServices: [
    {
      slug: 'random-cat',
      name: '随机猫咪图片',
      description: '获取一张随机猫咪图片',
      category: 'image',
      targetUrl: 'https://api.thecatapi.com/v1/images/search',
      method: 'GET',
      params: [{ name: 'limit', type: 'number', required: false, description: '返回数量（1-10）' }],
      inputExample: '{}',
      outputExample: '[{"id":"abc","url":"https://cdn2.thecatapi.com/images/abc.jpg","width":500,"height":500}]',
    },
    {
      slug: 'random-user',
      name: '随机用户生成',
      description: '生成随机用户信息（姓名、邮箱、头像、地址等）',
      category: 'data',
      targetUrl: 'https://randomuser.me/api/',
      method: 'GET',
      params: [
        { name: 'gender', type: 'string', required: false, description: '性别：male 或 female' },
        { name: 'nat', type: 'string', required: false, description: '国籍代码，如 US, GB, FR' },
      ],
      inputExample: '{"gender": "male", "nat": "US"}',
      outputExample: '{"results":[{"name":{"first":"John","last":"Doe"},"email":"john.doe@example.com","picture":{"large":"https://..."}}]}',
    },
    {
      slug: 'ip-lookup',
      name: 'IP地址查询',
      description: '通过IP地址查询地理位置信息（国家、城市、ISP等）',
      category: 'network',
      targetUrl: 'http://ip-api.com/json/{{ip}}?lang=zh-CN',
      method: 'GET',
      params: [{ name: 'ip', type: 'string', required: true, description: '要查询的IP地址' }],
      inputExample: '{"ip": "8.8.8.8"}',
      outputExample: '{"country":"美国","city":"山景城","isp":"Google LLC","query":"8.8.8.8"}',
    },
    {
      slug: 'random-joke',
      name: '随机笑话',
      description: '获取一条随机中英文笑话',
      category: 'text',
      targetUrl: 'https://v2.jokeapi.dev/joke/Any?lang=zh',
      method: 'GET',
      params: [],
      inputExample: '{}',
      outputExample: '{"type":"twopart","setup":"为什么程序员不喜欢出门？","delivery":"因为外面有太多bug！","category":"Programming"}',
    },
  ],
};
